language: elixir
elixir: 1.0.5
otp_release:
  - 17.4
sudo: false
before_install:
  - cp config/credentials.exs.example config/credentials.exs
before_script:
  - mix deps.get --only test
script:
  - MIX_ENV=test mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
